#!/bin/sh

REPO=$1

if [ -z "$1" ]; then
	echo "No repo specified" 1>&2
	exit 3
fi

VAL=$(curl -s https://api.travis-ci.org/repos/$REPO/builds | jshon -Q -e 0 -e result)

if [ $? == 1 ]; then
	VAL=2
fi

exit $VAL
